name: Workflow3

on:
  workflow_dispatch:
      
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: Ejecutar tests
        run: mvn test
        
      - name: Crear imagen Docker 
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: 
          COMMIT_HASH=$(echo "${{ github.ref }}" | cut -d'/' -f3)
          IMAGE_TAG="release-${COMMIT_HASH}"
          mvn spring-boot:build-image -Dspring-boot.build-imageName=$DOCKER_USERNAME/practica_3_testing:$IMAGE_TAG
          docker push $DOCKER_USERNAME/practica_3_testing:$IMAGE_TAG
        
      
