name: Workflow1

on:
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Comprobar repositorio
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
            distribution: 'temurin'
            java-version: '17'

      - name: Ejecutar tests (pruebas unitarias y de integración)
        run: mvn test
