name: Workflow3

on:
  workflow_dispatch:
      
jobs:
  publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: Ejecutar tests
        run: mvn test
        
      - name: Crear imagen Docker 
        run: mvn spring-boot:build-image -DskipTests
          -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/books-reviewer:${{ github.sha }} 
          
      - name: Iniciar sesion en DockerHub
        run: docker login 
          -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
        
      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/books-reviewer:${{ github.sha }}
          
      - name: Instalar el cliente de Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
        
      - name: Iniciar sesion en Okteto
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
        
      - name: Desplegar en Okteto
        run: |
          export VERSION=${{ github.sha }}
          okteto deploy --wait
