name: Workflow 2

on: 
  push: 
    branches: 
      - master
      
jobs: 
  test: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Comprobar repositorio
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
            
      - name: Ejecucion de los test 
      - run: mvn test
            
          
          
