name: Workflow4

on:
  schedule: 
    - cron: '0 2 * * *' #Ejecucion a las 04:00h hora española aproximadamente (02:00h UTC)
  
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: Ejecutar tests
        run: mvn test -Dtest=!SanityTest
        
      - name: Generar el tag para la version de la imagen docker 
        run:  echo "tag=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
        id: timestamp
        
      - name: Generamos la imagen docker
        run: mvn spring-boot:build-image -DskipTests
          -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/books-reviewer:dev-${{ steps.timestamp.outputs.tag }}.
          
      - name: Iniciar sesion en DockerHub
        run: docker login 
          -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
        
      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/books-reviewer:dev-${{ steps.timestamp.outputs.tag }}.
