name: Workflow1

on: 
  workflow_dispatch:
  #pull_request: 
    #branches: 
      #- master
    
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: Ejecucion de test de integracion 
        run: mvn test -Dtest=integration
        
      - name: Ejecucion de test unitarios 
        run: mvn test -Dtest=unitary
          
      
      
